kafka:
  brokers:
    - ${KAFKA_NOTIF_URL}
  group_id: notif-email-consumer
  topic: "notif.email.register.confirm"

smtp:
  username: ${SMTP_MAIL_ADRESS}
  password: ${SMTP_PASSWORD}
  host: "smtp.gmail.com"
  port: 587
