scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:9123"]

  # - job_name: 'system'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

