grpcclient:
  target: "localhost:50051"

kafka:
  network: "tcp"
  broker: "localhost:9092"
  topic: "notif.email.register.confirm"
  partion: 0
  write_deadline: 10

httpserver:
  listen: ":8081"

postgres:
  host: localhost
  port: 5432
  user: postgres
  db_name: jxger_bank

redis:
  adress: localhost:6379
  index: 0
  pool_size: 1024
  min_idle_conn: 30