grpc_target: "localhost:500051"

kafka: 
  network: "tcp"
  adress: "localhost:9092"
  topic: "notif.email.register.confirm"
  partion: 0

httpserver:
  listen: ":8081"

postgres:
  host: localhost
  port: 5432
  user: root
  db_name: jxger_bank

redis:
  adress: localhost:6379
  index: 0
  pool_size: 1024
  min_idle_conn: 30